version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATA_PATH=/app/data
      - DEBUG=${DEBUG}
    volumes:
      - ./backend:/app
      - ./data:/app/data:ro
      - /share/data:/share/data:ro
      - /home/xyy/SIAT_CAS/xu/tracing/swc_collect:/home/xyy/SIAT_CAS/xu/tracing/swc_collect:ro
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  redis_data:
